// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api/v1/profile.proto

package profile_v1

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "github.com/mwitkow/go-proto-validators"
	time "time"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

func (this *Profile) Validate() error {
	if this.CreateDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreateDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreateDate", err)
		}
	}
	if this.UpdateDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdateDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdateDate", err)
		}
	}
	return nil
}
func (this *CreateProfileReq) Validate() error {
	if this.FirstName == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("FirstName", fmt.Errorf(`must not be empty`))
	}
	if this.LastName == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("LastName", fmt.Errorf(`must not be empty`))
	}
	return nil
}
func (this *ReadProfileReq) Validate() error {
	return nil
}
func (this *DeleteProfileRes) Validate() error {
	return nil
}
func (this *ListProfilesRes) Validate() error {
	if this.Profile != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Profile); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Profile", err)
		}
	}
	return nil
}
